### ISSUE TITLE
Support an authorization layer for derived resources

### ISSUE THREAD

**Issue by phochste** [SolidLabResearch/derived-resources-component#5]
When creating a selector for derived resources, some of the resource could be not readable for the agent that is accessing the dervired resource. The derived resource should always check the authorizations of a resource before it can be used in the selector.

E.g. what fails:

```
<> a <http://www.w3.org/ns/pim/space#Storage>;
    derived:derivedResource [
        derived:template "demo2";
        derived:selector <data2/*> , <data2/nested/*>;
        derived:filter <demo2-filter>
    ].
```

and a container structure:

```
data2/
  nested/
     .acl <- providing no read access for public for all resources
     1$.ttl
  2$.ttl
  3$.ttl
```

In the current implementation the data of `1$.ttl` is available for the public.

**Comment by joachimvh** [comment]
Authorization is still an ongoing discussion as it does get more complicated for these kinds of resources. One of the goals of derived resources is to provide users "partial" access to resources they should not be able to read fully. So just because someone does not have read access to `data2/nested/1` here does not mean they should not be able to read a derived resource containing input of that resource.

The current idea is to check the permissions of the client that creates a new derived resource. E.g., when doing a PATCH to metadata with triples that define a new derived resource, check if that client has read permissions on all selectors. Although this is still not perfect as permissions can change afterwards, and new resources can be added when using wildcards, but that should already remove the biggest issues.
